# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # The GooglePay Token Payment Request
  class CreateGooglePayRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The token version
    # @return [String]
    attr_accessor :version

    # The cryptography data
    # @return [String]
    attr_accessor :data

    # The GooglePay header request
    # @return [CreateGooglePayHeaderRequest]
    attr_accessor :header

    # Detached PKCS #7 signature, Base64 encoded as string
    # @return [String]
    attr_accessor :signature

    # GooglePay Merchant identifier
    # @return [String]
    attr_accessor :merchant_identifier

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['version'] = 'version'
      @_hash['data'] = 'data'
      @_hash['header'] = 'header'
      @_hash['signature'] = 'signature'
      @_hash['merchant_identifier'] = 'merchant_identifier'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(version = nil,
                   data = nil,
                   header = nil,
                   signature = nil,
                   merchant_identifier = nil)
      @version = version unless version == SKIP
      @data = data unless data == SKIP
      @header = header unless header == SKIP
      @signature = signature unless signature == SKIP
      @merchant_identifier = merchant_identifier unless merchant_identifier == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      version = hash.key?('version') ? hash['version'] : SKIP
      data = hash.key?('data') ? hash['data'] : SKIP
      header = CreateGooglePayHeaderRequest.from_hash(hash['header']) if hash['header']
      signature = hash.key?('signature') ? hash['signature'] : SKIP
      merchant_identifier =
        hash.key?('merchant_identifier') ? hash['merchant_identifier'] : SKIP

      # Create object from extracted values.
      CreateGooglePayRequest.new(version,
                                 data,
                                 header,
                                 signature,
                                 merchant_identifier)
    end
  end
end
