# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # CreateCardPayloadRequest Model.
  class CreateCardPayloadRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [CreateGooglePayRequest]
    attr_accessor :google_pay

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['google_pay'] = 'google_pay'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        google_pay
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        type
        google_pay
      ]
    end

    def initialize(type = SKIP, google_pay = SKIP)
      @type = type unless type == SKIP
      @google_pay = google_pay unless google_pay == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      google_pay = CreateGooglePayRequest.from_hash(hash['google_pay']) if hash['google_pay']

      # Create object from extracted values.
      CreateCardPayloadRequest.new(type,
                                   google_pay)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, google_pay: #{@google_pay}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, google_pay: #{@google_pay.inspect}>"
    end
  end
end
