# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # The settings for creating a private label payment
  class CreatePrivateLabelPaymentRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Number of installments
    # @return [Integer]
    attr_accessor :installments

    # The text that will be shown on the private label's statement
    # @return [String]
    attr_accessor :statement_descriptor

    # Card data
    # @return [CreateCardRequest]
    attr_accessor :card

    # The Card id
    # @return [String]
    attr_accessor :card_id

    # The Card id
    # @return [String]
    attr_accessor :card_token

    # Indicates a recurrence
    # @return [Boolean]
    attr_accessor :recurrence

    # Indicates if the operation should be only authorization or auth and
    # capture.
    # @return [Boolean]
    attr_accessor :capture

    # Indicates whether the extended label (private label) is enabled
    # @return [Boolean]
    attr_accessor :extended_limit_enabled

    # Extended Limit Code
    # @return [String]
    attr_accessor :extended_limit_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['installments'] = 'installments'
      @_hash['statement_descriptor'] = 'statement_descriptor'
      @_hash['card'] = 'card'
      @_hash['card_id'] = 'card_id'
      @_hash['card_token'] = 'card_token'
      @_hash['recurrence'] = 'recurrence'
      @_hash['capture'] = 'capture'
      @_hash['extended_limit_enabled'] = 'extended_limit_enabled'
      @_hash['extended_limit_code'] = 'extended_limit_code'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        installments
        statement_descriptor
        card
        card_id
        card_token
        recurrence
        capture
        extended_limit_enabled
        extended_limit_code
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(installments = 1,
                   statement_descriptor = nil,
                   card = nil,
                   card_id = nil,
                   card_token = nil,
                   recurrence = nil,
                   capture = true,
                   extended_limit_enabled = nil,
                   extended_limit_code = nil)
      @installments = installments unless installments == SKIP
      @statement_descriptor = statement_descriptor unless statement_descriptor == SKIP
      @card = card unless card == SKIP
      @card_id = card_id unless card_id == SKIP
      @card_token = card_token unless card_token == SKIP
      @recurrence = recurrence unless recurrence == SKIP
      @capture = capture unless capture == SKIP
      @extended_limit_enabled = extended_limit_enabled unless extended_limit_enabled == SKIP
      @extended_limit_code = extended_limit_code unless extended_limit_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      installments = hash['installments'] ||= 1
      statement_descriptor =
        hash.key?('statement_descriptor') ? hash['statement_descriptor'] : SKIP
      card = CreateCardRequest.from_hash(hash['card']) if hash['card']
      card_id = hash.key?('card_id') ? hash['card_id'] : SKIP
      card_token = hash.key?('card_token') ? hash['card_token'] : SKIP
      recurrence = hash.key?('recurrence') ? hash['recurrence'] : SKIP
      capture = hash['capture'] ||= true
      extended_limit_enabled =
        hash.key?('extended_limit_enabled') ? hash['extended_limit_enabled'] : SKIP
      extended_limit_code =
        hash.key?('extended_limit_code') ? hash['extended_limit_code'] : SKIP

      # Create object from extracted values.
      CreatePrivateLabelPaymentRequest.new(installments,
                                           statement_descriptor,
                                           card,
                                           card_id,
                                           card_token,
                                           recurrence,
                                           capture,
                                           extended_limit_enabled,
                                           extended_limit_code)
    end
  end
end
