# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # The GooglePay Intermediate Signing Key Request
  class CreateGooglePayIntermediateSigningKeyRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Uma mensagem codificada em Base64 com a descrição de pagamento da chave.
    # @return [String]
    attr_accessor :signed_key

    # Verifica se a origem da chave de assinatura intermediária é o Google. É
    # codificada em Base64 e criada usando o ECDSA.
    # @return [Array[String]]
    attr_accessor :signatures

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['signed_key'] = 'signed_key'
      @_hash['signatures'] = 'signatures'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(signed_key = nil,
                   signatures = nil)
      @signed_key = signed_key
      @signatures = signatures
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      signed_key = hash.key?('signed_key') ? hash['signed_key'] : nil
      signatures = hash.key?('signatures') ? hash['signatures'] : nil

      # Create object from extracted values.
      CreateGooglePayIntermediateSigningKeyRequest.new(signed_key,
                                                       signatures)
    end
  end
end
