# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # CreateSellerRequest Model.
  class CreateSellerRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Name
    # @return [String]
    attr_accessor :name

    # Seller's code identification
    # @return [String]
    attr_accessor :code

    # Description
    # @return [String]
    attr_accessor :description

    # Document number (individual / company)
    # @return [String]
    attr_accessor :document

    # Address
    # @return [CreateAddressRequest]
    attr_accessor :address

    # Person type (individual / company)
    # @return [String]
    attr_accessor :type

    # Metadata
    # @return [Hash]
    attr_accessor :metadata

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['code'] = 'code'
      @_hash['description'] = 'description'
      @_hash['document'] = 'document'
      @_hash['address'] = 'address'
      @_hash['type'] = 'type'
      @_hash['metadata'] = 'metadata'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        code
        description
        document
        address
        type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(name = nil,
                   metadata = nil,
                   code = nil,
                   description = nil,
                   document = nil,
                   address = nil,
                   type = nil)
      @name = name unless name == SKIP
      @code = code unless code == SKIP
      @description = description unless description == SKIP
      @document = document unless document == SKIP
      @address = address unless address == SKIP
      @type = type unless type == SKIP
      @metadata = metadata unless metadata == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      code = hash.key?('code') ? hash['code'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      document = hash.key?('document') ? hash['document'] : SKIP
      address = CreateAddressRequest.from_hash(hash['address']) if hash['address']
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      CreateSellerRequest.new(name,
                              metadata,
                              code,
                              description,
                              document,
                              address,
                              type)
    end
  end
end
