# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module PagarmeApiSdk
  # Token data
  class GetTokenResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :created_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :expires_at

    # TODO: Write general description for this method
    # @return [GetCardTokenResponse]
    attr_accessor :card

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash['created_at'] = 'created_at'
      @_hash['expires_at'] = 'expires_at'
      @_hash['card'] = 'card'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        type
        created_at
        expires_at
        card
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        id
        type
        created_at
        expires_at
        card
      ]
    end

    def initialize(id = SKIP, type = SKIP, created_at = SKIP, expires_at = SKIP,
                   card = SKIP)
      @id = id unless id == SKIP
      @type = type unless type == SKIP
      @created_at = created_at unless created_at == SKIP
      @expires_at = expires_at unless expires_at == SKIP
      @card = card unless card == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      created_at = if hash.key?('created_at')
                     (DateTimeHelper.from_rfc3339(hash['created_at']) if hash['created_at'])
                   else
                     SKIP
                   end
      expires_at = hash.key?('expires_at') ? hash['expires_at'] : SKIP
      card = GetCardTokenResponse.from_hash(hash['card']) if hash['card']

      # Create object from extracted values.
      GetTokenResponse.new(id,
                           type,
                           created_at,
                           expires_at,
                           card)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, type: #{@type}, created_at: #{@created_at}, expires_at:"\
      " #{@expires_at}, card: #{@card}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, type: #{@type.inspect}, created_at:"\
      " #{@created_at.inspect}, expires_at: #{@expires_at.inspect}, card: #{@card.inspect}>"
    end
  end
end
