# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require_relative 'get_transaction_response'

module PagarmeApiSdk
  # Response object when getting a pix transaction
  class GetPixTransactionResponse < GetTransactionResponse
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :qr_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :qr_code_url

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :expires_at

    # TODO: Write general description for this method
    # @return [Array[PixAdditionalInformation]]
    attr_accessor :additional_information

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :end_to_end_id

    # TODO: Write general description for this method
    # @return [GetPixPayerResponse]
    attr_accessor :payer

    # Pix provider TID
    # @return [String]
    attr_accessor :pix_provider_tid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['qr_code'] = 'qr_code'
      @_hash['qr_code_url'] = 'qr_code_url'
      @_hash['expires_at'] = 'expires_at'
      @_hash['additional_information'] = 'additional_information'
      @_hash['end_to_end_id'] = 'end_to_end_id'
      @_hash['payer'] = 'payer'
      @_hash['pix_provider_tid'] = 'pix_provider_tid'
      @_hash = super().merge(@_hash)
      @_hash
    end

    # An array for optional fields
    def self.optionals
      _arr = %w[
        qr_code
        qr_code_url
        expires_at
        additional_information
        end_to_end_id
        payer
        pix_provider_tid
      ]
      (_arr << super()).flatten!
    end

    # An array for nullable fields
    def self.nullables
      _arr = %w[
        qr_code
        qr_code_url
        expires_at
        additional_information
        end_to_end_id
        payer
        pix_provider_tid
      ]
      (_arr << super()).flatten!
    end

    def initialize(qr_code = SKIP,
                   qr_code_url = SKIP,
                   expires_at = SKIP,
                   additional_information = SKIP,
                   end_to_end_id = SKIP,
                   payer = SKIP,
                   pix_provider_tid = SKIP,
                   gateway_id = SKIP,
                   amount = SKIP,
                   status = SKIP,
                   success = SKIP,
                   created_at = SKIP,
                   updated_at = SKIP,
                   attempt_count = SKIP,
                   max_attempts = SKIP,
                   splits = SKIP,
                   next_attempt = SKIP,
                   transaction_type = 'pix',
                   id = SKIP,
                   gateway_response = SKIP,
                   antifraud_response = SKIP,
                   metadata = SKIP,
                   split = SKIP,
                   interest = SKIP,
                   fine = SKIP,
                   max_days_to_pay_past_due = SKIP)
      @qr_code = qr_code unless qr_code == SKIP
      @qr_code_url = qr_code_url unless qr_code_url == SKIP
      @expires_at = expires_at unless expires_at == SKIP
      @additional_information = additional_information unless additional_information == SKIP
      @end_to_end_id = end_to_end_id unless end_to_end_id == SKIP
      @payer = payer unless payer == SKIP
      @pix_provider_tid = pix_provider_tid unless pix_provider_tid == SKIP

      # Call the constructor of the base class
      super(gateway_id,
            amount,
            status,
            success,
            created_at,
            updated_at,
            attempt_count,
            max_attempts,
            splits,
            next_attempt,
            transaction_type,
            id,
            gateway_response,
            antifraud_response,
            metadata,
            split,
            interest,
            fine,
            max_days_to_pay_past_due)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      qr_code = hash.key?('qr_code') ? hash['qr_code'] : SKIP
      qr_code_url = hash.key?('qr_code_url') ? hash['qr_code_url'] : SKIP
      expires_at = if hash.key?('expires_at')
                     (DateTimeHelper.from_rfc3339(hash['expires_at']) if hash['expires_at'])
                   else
                     SKIP
                   end
      # Parameter is an array, so we need to iterate through it
      additional_information = nil
      unless hash['additional_information'].nil?
        additional_information = []
        hash['additional_information'].each do |structure|
          additional_information << (PixAdditionalInformation.from_hash(structure) if structure)
        end
      end

      additional_information = SKIP unless hash.key?('additional_information')
      end_to_end_id = hash.key?('end_to_end_id') ? hash['end_to_end_id'] : SKIP
      payer = GetPixPayerResponse.from_hash(hash['payer']) if hash['payer']
      pix_provider_tid =
        hash.key?('pix_provider_tid') ? hash['pix_provider_tid'] : SKIP
      gateway_id = hash.key?('gateway_id') ? hash['gateway_id'] : SKIP
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      success = hash.key?('success') ? hash['success'] : SKIP
      created_at = if hash.key?('created_at')
                     (DateTimeHelper.from_rfc3339(hash['created_at']) if hash['created_at'])
                   else
                     SKIP
                   end
      updated_at = if hash.key?('updated_at')
                     (DateTimeHelper.from_rfc3339(hash['updated_at']) if hash['updated_at'])
                   else
                     SKIP
                   end
      attempt_count = hash.key?('attempt_count') ? hash['attempt_count'] : SKIP
      max_attempts = hash.key?('max_attempts') ? hash['max_attempts'] : SKIP
      # Parameter is an array, so we need to iterate through it
      splits = nil
      unless hash['splits'].nil?
        splits = []
        hash['splits'].each do |structure|
          splits << (GetSplitResponse.from_hash(structure) if structure)
        end
      end

      splits = SKIP unless hash.key?('splits')
      next_attempt = if hash.key?('next_attempt')
                       (DateTimeHelper.from_rfc3339(hash['next_attempt']) if hash['next_attempt'])
                     else
                       SKIP
                     end
      transaction_type = hash['transaction_type'] ||= 'pix'
      id = hash.key?('id') ? hash['id'] : SKIP
      gateway_response = GetGatewayResponseResponse.from_hash(hash['gateway_response']) if
        hash['gateway_response']
      antifraud_response = GetAntifraudResponse.from_hash(hash['antifraud_response']) if
        hash['antifraud_response']
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      # Parameter is an array, so we need to iterate through it
      split = nil
      unless hash['split'].nil?
        split = []
        hash['split'].each do |structure|
          split << (GetSplitResponse.from_hash(structure) if structure)
        end
      end

      split = SKIP unless hash.key?('split')
      interest = GetInterestResponse.from_hash(hash['interest']) if hash['interest']
      fine = GetFineResponse.from_hash(hash['fine']) if hash['fine']
      max_days_to_pay_past_due =
        hash.key?('max_days_to_pay_past_due') ? hash['max_days_to_pay_past_due'] : SKIP

      # Create object from extracted values.
      GetPixTransactionResponse.new(qr_code,
                                    qr_code_url,
                                    expires_at,
                                    additional_information,
                                    end_to_end_id,
                                    payer,
                                    pix_provider_tid,
                                    gateway_id,
                                    amount,
                                    status,
                                    success,
                                    created_at,
                                    updated_at,
                                    attempt_count,
                                    max_attempts,
                                    splits,
                                    next_attempt,
                                    transaction_type,
                                    id,
                                    gateway_response,
                                    antifraud_response,
                                    metadata,
                                    split,
                                    interest,
                                    fine,
                                    max_days_to_pay_past_due)
    end

    def to_custom_expires_at
      DateTimeHelper.to_rfc3339(expires_at)
    end
  end
end
