# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Anticipation limit
  class GetAnticipationLimitResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Amount
    # @return [Integer]
    attr_accessor :amount

    # Anticipation fee
    # @return [Integer]
    attr_accessor :anticipation_fee

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['anticipation_fee'] = 'anticipation_fee'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount
        anticipation_fee
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        amount
        anticipation_fee
      ]
    end

    def initialize(amount = SKIP, anticipation_fee = SKIP)
      @amount = amount unless amount == SKIP
      @anticipation_fee = anticipation_fee unless anticipation_fee == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      anticipation_fee =
        hash.key?('anticipation_fee') ? hash['anticipation_fee'] : SKIP

      # Create object from extracted values.
      GetAnticipationLimitResponse.new(amount,
                                       anticipation_fee)
    end
  end
end
