# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Payment Authentication response
  class GetPaymentAuthenticationResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # 3D-S payment authentication response
    # @return [GetThreeDSecureResponse]
    attr_accessor :threed_secure

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['threed_secure'] = 'threed_secure'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        threed_secure
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        type
        threed_secure
      ]
    end

    def initialize(type = SKIP, threed_secure = SKIP)
      @type = type unless type == SKIP
      @threed_secure = threed_secure unless threed_secure == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      threed_secure = GetThreeDSecureResponse.from_hash(hash['threed_secure']) if
        hash['threed_secure']

      # Create object from extracted values.
      GetPaymentAuthenticationResponse.new(type,
                                           threed_secure)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, threed_secure: #{@threed_secure}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, threed_secure: #{@threed_secure.inspect}>"
    end
  end
end
