# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Bank transfer checkout response
  class GetCheckoutBankTransferPaymentResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # bank list response
    # @return [Array[String]]
    attr_accessor :bank

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bank'] = 'bank'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        bank
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        bank
      ]
    end

    def initialize(bank = SKIP)
      @bank = bank unless bank == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bank = hash.key?('bank') ? hash['bank'] : SKIP

      # Create object from extracted values.
      GetCheckoutBankTransferPaymentResponse.new(bank)
    end
  end
end
