# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'get_movement_object_base_response'

module PagarmeApiSdk
  # Generic response object for getting a MovementObjectFeeCollection.
  class GetMovementObjectFeeCollectionResponse < GetMovementObjectBaseResponse
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :recipient_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['description'] = 'description'
      @_hash['payment_date'] = 'payment_date'
      @_hash['recipient_id'] = 'recipient_id'
      @_hash = super().merge(@_hash)
      @_hash
    end

    # An array for optional fields
    def self.optionals
      _arr = %w[
        description
        payment_date
        recipient_id
      ]
      (_arr << super()).flatten!
    end

    # An array for nullable fields
    def self.nullables
      _arr = %w[
        description
        payment_date
        recipient_id
      ]
      (_arr << super()).flatten!
    end

    def initialize(description = SKIP,
                   payment_date = SKIP,
                   recipient_id = SKIP,
                   object = 'feeCollection',
                   id = SKIP,
                   status = SKIP,
                   amount = SKIP,
                   created_at = SKIP,
                   type = SKIP,
                   charge_id = SKIP,
                   gateway_id = SKIP)
      @description = description unless description == SKIP
      @payment_date = payment_date unless payment_date == SKIP
      @recipient_id = recipient_id unless recipient_id == SKIP

      # Call the constructor of the base class
      super(object,
            id,
            status,
            amount,
            created_at,
            type,
            charge_id,
            gateway_id)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      description = hash.key?('description') ? hash['description'] : SKIP
      payment_date = hash.key?('payment_date') ? hash['payment_date'] : SKIP
      recipient_id = hash.key?('recipient_id') ? hash['recipient_id'] : SKIP
      object = hash['object'] ||= 'feeCollection'
      id = hash.key?('id') ? hash['id'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      created_at = hash.key?('created_at') ? hash['created_at'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      charge_id = hash.key?('charge_id') ? hash['charge_id'] : SKIP
      gateway_id = hash.key?('gateway_id') ? hash['gateway_id'] : SKIP

      # Create object from extracted values.
      GetMovementObjectFeeCollectionResponse.new(description,
                                                 payment_date,
                                                 recipient_id,
                                                 object,
                                                 id,
                                                 status,
                                                 amount,
                                                 created_at,
                                                 type,
                                                 charge_id,
                                                 gateway_id)
    end
  end
end
