# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Response object for getting an invoice item
  class GetInvoiceItemResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :amount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [GetPricingSchemeResponse]
    attr_accessor :pricing_scheme

    # TODO: Write general description for this method
    # @return [GetPriceBracketResponse]
    attr_accessor :price_bracket

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # Subscription Item Id
    # @return [String]
    attr_accessor :subscription_item_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['description'] = 'description'
      @_hash['pricing_scheme'] = 'pricing_scheme'
      @_hash['price_bracket'] = 'price_bracket'
      @_hash['quantity'] = 'quantity'
      @_hash['name'] = 'name'
      @_hash['subscription_item_id'] = 'subscription_item_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount
        description
        pricing_scheme
        price_bracket
        quantity
        name
        subscription_item_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        amount
        description
        pricing_scheme
        price_bracket
        quantity
        name
        subscription_item_id
      ]
    end

    def initialize(amount = SKIP,
                   description = SKIP,
                   pricing_scheme = SKIP,
                   price_bracket = SKIP,
                   quantity = SKIP,
                   name = SKIP,
                   subscription_item_id = SKIP)
      @amount = amount unless amount == SKIP
      @description = description unless description == SKIP
      @pricing_scheme = pricing_scheme unless pricing_scheme == SKIP
      @price_bracket = price_bracket unless price_bracket == SKIP
      @quantity = quantity unless quantity == SKIP
      @name = name unless name == SKIP
      @subscription_item_id = subscription_item_id unless subscription_item_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      pricing_scheme = GetPricingSchemeResponse.from_hash(hash['pricing_scheme']) if
        hash['pricing_scheme']
      price_bracket = GetPriceBracketResponse.from_hash(hash['price_bracket']) if
        hash['price_bracket']
      quantity = hash.key?('quantity') ? hash['quantity'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      subscription_item_id =
        hash.key?('subscription_item_id') ? hash['subscription_item_id'] : SKIP

      # Create object from extracted values.
      GetInvoiceItemResponse.new(amount,
                                 description,
                                 pricing_scheme,
                                 price_bracket,
                                 quantity,
                                 name,
                                 subscription_item_id)
    end
  end
end
