# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # GetChargesSummaryResponse Model.
  class GetChargesSummaryResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['total'] = 'total'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        total
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        total
      ]
    end

    def initialize(total = SKIP)
      @total = total unless total == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      total = hash.key?('total') ? hash['total'] : SKIP

      # Create object from extracted values.
      GetChargesSummaryResponse.new(total)
    end
  end
end
