# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Response object for getting an PhoneNumberResponse
  class GetPhoneNumberResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ddd

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ddd'] = 'ddd'
      @_hash['number'] = 'number'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ddd
        number
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        ddd
        number
        type
      ]
    end

    def initialize(ddd = SKIP, number = SKIP, type = SKIP)
      @ddd = ddd unless ddd == SKIP
      @number = number unless number == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ddd = hash.key?('ddd') ? hash['ddd'] : SKIP
      number = hash.key?('number') ? hash['number'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      GetPhoneNumberResponse.new(ddd,
                                 number,
                                 type)
    end
  end
end
