# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module PagarmeApiSdk
  # GetCheckoutBoletoPaymentResponse Model.
  class GetCheckoutBoletoPaymentResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Data de vencimento do boleto
    # @return [DateTime]
    attr_accessor :due_at

    # Instruções do boleto
    # @return [String]
    attr_accessor :instructions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['due_at'] = 'due_at'
      @_hash['instructions'] = 'instructions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        due_at
        instructions
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        due_at
        instructions
      ]
    end

    def initialize(due_at = SKIP, instructions = SKIP)
      @due_at = due_at unless due_at == SKIP
      @instructions = instructions unless instructions == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      due_at = if hash.key?('due_at')
                 (DateTimeHelper.from_rfc3339(hash['due_at']) if hash['due_at'])
               else
                 SKIP
               end
      instructions = hash.key?('instructions') ? hash['instructions'] : SKIP

      # Create object from extracted values.
      GetCheckoutBoletoPaymentResponse.new(due_at,
                                           instructions)
    end

    def to_custom_due_at
      DateTimeHelper.to_rfc3339(due_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} due_at: #{@due_at}, instructions: #{@instructions}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} due_at: #{@due_at.inspect}, instructions: #{@instructions.inspect}>"
    end
  end
end
