# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Split response
  class GetSplitResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Type
    # @return [String]
    attr_accessor :type

    # Amount
    # @return [Integer]
    attr_accessor :amount

    # Recipient
    # @return [GetRecipientResponse]
    attr_accessor :recipient

    # The split rule gateway id
    # @return [String]
    attr_accessor :gateway_id

    # The split rule gateway id
    # @return [GetSplitOptionsResponse]
    attr_accessor :options

    # The split rule gateway id
    # @return [String]
    attr_accessor :id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['amount'] = 'amount'
      @_hash['recipient'] = 'recipient'
      @_hash['gateway_id'] = 'gateway_id'
      @_hash['options'] = 'options'
      @_hash['id'] = 'id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        amount
        recipient
        gateway_id
        options
        id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        type
        amount
        recipient
        gateway_id
        options
        id
      ]
    end

    def initialize(type = SKIP,
                   amount = SKIP,
                   recipient = SKIP,
                   gateway_id = SKIP,
                   options = SKIP,
                   id = SKIP)
      @type = type unless type == SKIP
      @amount = amount unless amount == SKIP
      @recipient = recipient unless recipient == SKIP
      @gateway_id = gateway_id unless gateway_id == SKIP
      @options = options unless options == SKIP
      @id = id unless id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      recipient = GetRecipientResponse.from_hash(hash['recipient']) if hash['recipient']
      gateway_id = hash.key?('gateway_id') ? hash['gateway_id'] : SKIP
      options = GetSplitOptionsResponse.from_hash(hash['options']) if hash['options']
      id = hash.key?('id') ? hash['id'] : SKIP

      # Create object from extracted values.
      GetSplitResponse.new(type,
                           amount,
                           recipient,
                           gateway_id,
                           options,
                           id)
    end
  end
end
