# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PagarmeApiSdk
  # Response object for listing payable objects
  class ListPayablesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The payable object
    # @return [Array[GetPayableResponse]]
    attr_accessor :data

    # Cursor paging response
    # @return [CursorPagingResponse]
    attr_accessor :paging

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash['paging'] = 'paging'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        data
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        data
      ]
    end

    def initialize(paging = nil, data = SKIP)
      @data = data unless data == SKIP
      @paging = paging
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      paging = CursorPagingResponse.from_hash(hash['paging']) if hash['paging']
      # Parameter is an array, so we need to iterate through it
      data = nil
      unless hash['data'].nil?
        data = []
        hash['data'].each do |structure|
          data << (GetPayableResponse.from_hash(structure) if structure)
        end
      end

      data = SKIP unless hash.key?('data')

      # Create object from extracted values.
      ListPayablesResponse.new(paging,
                               data)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} data: #{@data}, paging: #{@paging}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} data: #{@data.inspect}, paging: #{@paging.inspect}>"
    end
  end
end
