# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Pix Additional Information
  class PixAdditionalInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'Name'
      @_hash['value'] = 'Value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        value
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        name
        value
      ]
    end

    def initialize(name = SKIP, value = SKIP)
      @name = name unless name == SKIP
      @value = value unless value == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('Name') ? hash['Name'] : SKIP
      value = hash.key?('Value') ? hash['Value'] : SKIP

      # Create object from extracted values.
      PixAdditionalInformation.new(name,
                                   value)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, value: #{@value}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, value: #{@value.inspect}>"
    end
  end
end
