# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Api Error Exception
  class ErrorException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :errors

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :request

    # The constructor.
    # @param [String] reason The reason for raising an exception.
    # @param [HttpResponse] response The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] hash The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      return nil unless hash

      @message = hash.key?('message') ? hash['message'] : nil
      @errors = hash.key?('errors') ? hash['errors'] : nil
      @request = hash.key?('request') ? hash['request'] : nil
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} message: #{@message}, errors: #{@errors}, request: #{@request}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} message: #{@message.inspect}, errors: #{@errors.inspect}, request:"\
      " #{@request.inspect}>"
    end
  end
end
