# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PagarmeApiSdk
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
