# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
