# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PagarmeApiSdk
  # An enum for SDK environments.
  class Environment
    ENVIRONMENT = [
      PRODUCTION = 'production'.freeze
    ].freeze

    # Converts a string or symbol into a valid Environment constant.
    def self.from_value(value, default_value = PRODUCTION)
      return default_value if value.nil?

      default_value
    end
  end

  # An enum for API servers.
  class Server
    SERVER = [
      DEFAULT = 'default'.freeze
    ].freeze

    # Converts a string or symbol into a valid Server constant.
    def self.from_value(value, default_value = DEFAULT)
      return default_value if value.nil?

      default_value
    end
  end

  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration < CoreLibrary::HttpClientConfiguration
    def basic_auth_user_name
      @basic_auth_credentials.username
    end

    def basic_auth_password
      @basic_auth_credentials.password
    end

    # The attribute readers for properties.
    attr_reader :environment, :basic_auth_credentials, :service_referer_name

    class << self
      attr_reader :environments
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil, proxy_settings: nil,
      environment: Environment::PRODUCTION, basic_auth_user_name: nil,
      basic_auth_password: nil, basic_auth_credentials: nil,
      service_referer_name: 'TODO: Replace'
    )
      super connection: connection, adapter: adapter, timeout: timeout,
            max_retries: max_retries, retry_interval: retry_interval,
            backoff_factor: backoff_factor, retry_statuses: retry_statuses,
            retry_methods: retry_methods, http_callback: http_callback,
            proxy_settings: proxy_settings

      # Current API environment
      @environment = String(environment)

      # The username to use with basic authentication
      @basic_auth_user_name = basic_auth_user_name

      # The password to use with basic authentication
      @basic_auth_password = basic_auth_password

      # TODO: Replace
      @service_referer_name = service_referer_name

      # Initializing Basic Authentication credentials with the provided auth parameters
      @basic_auth_credentials = create_auth_credentials_object(
        basic_auth_user_name, basic_auth_password, basic_auth_credentials
      )

      # The Http Client to use for making requests.
      set_http_client CoreLibrary::FaradayClient.new(self)
    end

    def clone_with(connection: nil, adapter: nil, timeout: nil,
                   max_retries: nil, retry_interval: nil, backoff_factor: nil,
                   retry_statuses: nil, retry_methods: nil, http_callback: nil,
                   proxy_settings: nil, environment: nil,
                   basic_auth_user_name: nil, basic_auth_password: nil,
                   basic_auth_credentials: nil, service_referer_name: nil)
      connection ||= self.connection
      adapter ||= self.adapter
      timeout ||= self.timeout
      max_retries ||= self.max_retries
      retry_interval ||= self.retry_interval
      backoff_factor ||= self.backoff_factor
      retry_statuses ||= self.retry_statuses
      retry_methods ||= self.retry_methods
      http_callback ||= self.http_callback
      proxy_settings ||= self.proxy_settings
      environment ||= self.environment
      service_referer_name ||= self.service_referer_name
      basic_auth_credentials = create_auth_credentials_object(
        basic_auth_user_name, basic_auth_password,
        basic_auth_credentials || self.basic_auth_credentials
      )

      Configuration.new(connection: connection, adapter: adapter,
                        timeout: timeout, max_retries: max_retries,
                        retry_interval: retry_interval,
                        backoff_factor: backoff_factor,
                        retry_statuses: retry_statuses,
                        retry_methods: retry_methods,
                        http_callback: http_callback,
                        proxy_settings: proxy_settings,
                        environment: environment,
                        service_referer_name: service_referer_name,
                        basic_auth_credentials: basic_auth_credentials)
    end

    def create_auth_credentials_object(basic_auth_user_name,
                                       basic_auth_password,
                                       basic_auth_credentials)
      return basic_auth_credentials if basic_auth_user_name.nil? && basic_auth_password.nil?

      warn('The \'basic_auth_user_name\', \'basic_auth_password\' params are d'\
           'eprecated. Use \'basic_auth_credentials\' param instead.')

      unless basic_auth_credentials.nil?
        return basic_auth_credentials.clone_with(
          username: basic_auth_user_name,
          password: basic_auth_password
        )
      end

      BasicAuthCredentials.new(username: basic_auth_user_name,
                               password: basic_auth_password)
    end

    # All the environments the SDK can run in.
    ENVIRONMENTS = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'https://api.pagar.me/core/v5'
      }
    }.freeze

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] server The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def get_base_uri(server = Server::DEFAULT)
      ENVIRONMENTS[environment][server].clone
    end

    # Builds a Configuration instance using environment variables.
    def self.build_default_config_from_env
      # === Core environment ===
      environment = Environment.from_value(ENV.fetch('ENVIRONMENT', 'production'))
      service_referer_name = ENV.fetch('SERVICE_REFERER_NAME', 'TODO: Replace')
      timeout = (ENV['TIMEOUT'] || 60).to_f
      max_retries = (ENV['MAX_RETRIES'] || 0).to_i
      retry_interval = (ENV['RETRY_INTERVAL'] || 1).to_f
      backoff_factor = (ENV['BACKOFF_FACTOR'] || 2).to_f
      retry_statuses = ENV.fetch('RETRY_STATUSES',
                                 '[408, 413, 429, 500, 502, 503, 504, 521, 522, 524]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end
      retry_methods = ENV.fetch('RETRY_METHODS', '%i[get put]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end

      # === Authentication credentials ===
      basic_auth_credentials = BasicAuthCredentials.from_env

      # === Proxy settings ===
      proxy_settings = ProxySettings.from_env

      Configuration.new(
        environment: environment,
        service_referer_name: service_referer_name,
        timeout: timeout,
        max_retries: max_retries,
        retry_interval: retry_interval,
        backoff_factor: backoff_factor,
        retry_statuses: retry_statuses,
        retry_methods: retry_methods,
        basic_auth_credentials: basic_auth_credentials,
        proxy_settings: proxy_settings
      )
    end
  end
end
