# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PagarmeApiSdk
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
