# pagarme_api_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PagarmeApiSdk
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
